### ISSUE TITLE
Redis Manager

### ISSUE THREAD

**Issue by HongJinFeng** [duzhipeng/duzhipeng.github.io#1]
大佬，请问您是不是重复购买了一个叫做Redis Manager的插件，我是插件的作者，在后台看到又一个账号为DU ZHI PENG的用户重复购买了，不知是不是您购买重复了。由于不知道您的邮箱，不知道这个github是不是您。如果不是，请忽略，如果是，请及时联系我，确定一下是否重复购买了，如果重复购买了，我这边看下如果给您退一下。理论上来说，同个账号只需要购买一次，就可以在所有地方使用。
![image](https://user-images.githubusercontent.com/33616750/114373212-f44c6d00-9bb4-11eb-86b4-d69efd80abba.png)
![image](https://user-images.githubusercontent.com/33616750/114373236-fadae480-9bb4-11eb-9a43-e602d826d14b.png)

**Comment by duzhipeng** [comment]
我去……大哥，是我，你居然找到我了。
和我理解的不一样，我理解是我又直接续费了一年。我是在官方点击「renew subscription」按钮又付了一次，原因是看到是国人开发，就想多支持一下，所以我一直以为我的操作是买了1年，又买了1年，一共买了2年。
无论是否我理解错了，我想大哥都不用退了，本来我就是想多多支持。

**Comment by HongJinFeng** [comment]
> 我去……大哥，是我，你居然找到我了。
> 和我理解的不一样，我理解是我又直接续费了一年。我是在官方点击「Renew subscription」按钮又付了一次，原因是看到是国人开发，就想多支持一下，所以我一直以为我的操作是买了1年，又买了1年，一共买了2年。
> 无论是否我理解错了，我想大哥都不用退了，本来我就是想多多支持。

感谢支持，大哥我以为你买重复了。小弟在此拜谢。哈。
